# Generated by Django 2.1 on 2020-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
